
source 'https://github.com/ZLJZ/PGSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'PGInfoKit_Example' do
  pod 'PGInfoKit', :path => '../'

  target 'PGInfoKit_Tests' do
    inherit! :search_paths

    
  end
end
